# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
---

name: Build with Gradle

on:
  push:
    branches: ["main"]
    paths:
      - "src/**"
      - ".github/workflows/build.yaml"
      - "gradle/**"
      - "build.gradle.kts"
      - "gradle.properties"
      - "settings.gradle.kts"
  pull_request:
    branches: ["main"]
    paths:
      - "src/**"
      - ".github/workflows/build.yaml"
      - "gradle/**"
      - "build.gradle.kts"
      - "gradle.properties"
      - "settings.gradle.kts"

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-22.04
    environment: Staging

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libgcc-12-dev libstdc++-12-dev libssl-dev libcurl4-openssl-dev
      # The Kotlin native compiler refuses to look for these object files in the right location
      - name: Copy crt objects
        run: sudo cp /usr/lib/x86_64-linux-gnu/crt* /usr/lib/
      - name: Store GitHub private key
        env:
          SECRET_KEY: ${{secrets.GH_APP_PRIVATE_PEM_KEYFILE}}
        run: echo "$SECRET_KEY" > github_private_key.pem
      - name: Store SSH private key
        env:
          PRIVATE_KEY: ${{secrets.WEBHOOK_TEST_KEY_CONTENTS}}
        run: echo "$PRIVATE_KEY" > id_rsa
      - name: Build with Gradle
        uses: gradle/gradle-build-action@356abb47e7664b5505e25d7997a5a522a17c62d9
        env:
          GITHUB_APP_PRIVATE_PEM_KEYFILE: github_private_key.pem
          GITHUB_APP_ID: ${{secrets.GH_APP_ID}}
          WEBHOOK_TEST_KEY: id_rsa
        with:
          arguments: build --info
