# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
---

name: Build with Gradle

on:
  push:
    branches: ["main"]
    paths:
      - "src/**"
      - ".github/workflows/build.yaml"
      - "gradle/**"
      - "build.gradle.kts"
      - "gradle.properties"
      - "settings.gradle.kts"
  pull_request:
    branches: ["main"]
    paths:
      - "src/**"
      - ".github/workflows/build.yaml"
      - "gradle/**"
      - "build.gradle.kts"
      - "gradle.properties"
      - "settings.gradle.kts"

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libgcc-12-dev libstdc++-12-dev libssl-dev libcurl4-openssl-dev
      # The Kotlin native compiler refuses to look for these object files in the right location
      - name: Copy crt objects
        run: sudo cp /usr/lib/x86_64-linux-gnu/crt* /usr/lib/
      - name: Store private key
        env:
          SECRET_KEY: ${{secrets.SECRET_PEM_KEYFILE}}
        run: echo "$SECRET_KEY" > github_private_key.pem
      - name: Build with Gradle
        uses: gradle/gradle-build-action@c295a4096e1d2c453eaf1f65c6f96686e26bd8be
        env:
          GITHUB_APP_PRIVATE_PEM_KEYFILE: github_private_key.pem
          GITHUB_APP_ID: ${{secrets.APP_ID}}
        with:
          arguments: build --info
